version: '3'
services:

    swapclient:
        image: i_swapclient
        stop_grace_period: 5m
        build:
            context: ../
        volumes:
            - ${COINDATA_PATH}:/coindata
        ports:
            - "${HTML_PORT}"  # Expose only to localhost, see .env
        environment:
            - TZ

volumes:
  coindata:
    driver: local

